### ISSUE TITLE
显示器黑屏问题

### ISSUE THREAD

**Issue by xuedingesmiao** [yunWJR/Hackintosh-deskmini-efi#1]
我是戴尔的u2415显示器，用的dp接口，各方面都很完美，就是有时候显示器会黑一下屏然后又正常了，不知道你有没有碰到过这个问题

**Comment by yunWJR** [comment]
我用的hdmi接口，没有黑屏过

**Comment by xuedingesmiao** [comment]
那我换hdmi试试，如果hdmi没问题，那估计是dp接口驱动估计有点问题。
